numero_telefono = int (31434232)
numero_amigo = int (31245636)
disponible = str (True)
inicio_llamada = float (7.30)
fin_llamada = float (9.30)
duracion_llamada = (inicio_llamada + fin_llamada)

print ("su numero es", numero_telefono)
print ("el numeor de tu amigo es", numero_amigo)
print ("tu amigo esta disponible", disponible)
print ("realizaste tu llamada a las", inicio_llamada)
print ("tu llamada finalizo a las ", fin_llamada)
print ("el timpo que duro la llamada fue de", duracion_llamada)